### PR TITLE
Save tile size, hgap, and vgap

### LINKED ISSUE #209: Saving the layout doesn't save the grid size
Reloading a layout after changing the grid size doesn't work correctly. I believe the grid size is not saved.

### PR DESCRIPTION
**Pull request by SamCarlberg**
Breaks older save files
Fixes #209

### CODE REVIEW

**Comment by SamCarlberg** [comment]
@frcjenkins retest this please

File: app/src/test/java/edu/wpi/first/shuffleboard/app/json/DashboardTabPaneSaverTest.java [hunk 1]
```diff
@@ -1,66 +1,133 @@
...
+    components.register(new DummyBooleanBoxType());
   }
 
-  @AfterEach
-  public void tearDown() {
-    AsyncUtils.setAsyncRunner(FxUtils::runOnFxThread);
-    NetworkTableUtils.shutdown();
+  @AfterAll
+  public static void tearDown() {
+    Components.setDefault(new Components());
```
Comment (JLLeitschuh) [inline app/src/test/java/edu/wpi/first/shuffleboard/app/json/DashboardTabPaneSaverTest.java]: Generally, you shouldn't need to do this sort of thing in well decoupled software.

**Comment by SamCarlberg** [comment]
@bradamiller That's because the minimum tile size is 64x64. There's a bug (fixed in #306) that doesn't validate the user input so you're allowed to set the size below that, but the size is checked when it's set via `setTileSize`. The housekeeping PR also lowers the minimum tile size to 32x32.
