### PR TITLE
Fix multi-byte characters in strings in recordings

### LINKED ISSUE #487: Loading recordings barfs on strings containing code points > 255
**Describe the bug**  
Data recordings store characters in strings as 1-byte code points. Multi-byte characters (eg ™, ®, non-Latin letters) are saved correctly, but treated as 1-byte when calculating the length of the string

**To Reproduce**  
1. Have a source containing a string with a code point > 255, such as ®
2. Attempt to load the recording

### PR DESCRIPTION
**Pull request by SamCarlberg**
All chars were assumed to be 1 byte, causing issues with characters outside ASCII

Fixes #487

### CODE REVIEW

File: api/src/test/java/edu/wpi/first/shuffleboard/api/sources/recording/SerializationTest.java [hunk 1]
```diff
@@ -22,6 +22,10 @@
       0, 0, 0, 3, 'b', 'a', 'r'  // "bar", encoded with length
   };
 
+  // Grinning emoji, four bytes
+  @SuppressWarnings("AvoidEscapedUnicodeCharacters")
+  private static final String grinningEmoji = "\uD83D\uDE01";
```
Comment (AustinShalit) [inline api/src/test/java/edu/wpi/first/shuffleboard/api/sources/recording/SerializationTest.java]: Doesn't java support emojis in code now?  Can we put the emoji here instead of the escape sequence?

Comment (SamCarlberg) [reply api/src/test/java/edu/wpi/first/shuffleboard/api/sources/recording/SerializationTest.java]: Huh, I didn't know that. That'll make it easier

**Comment by AustinShalit** [comment]
@frcjenkins retest this please

**Comment by AustinShalit** [comment]
@frcjenkins test this please

**Comment by SamCarlberg** [comment]
@frcjenkins retest this please
