### PR TITLE
Exit properly when confirmation dialog not shown

### LINKED ISSUE #708: Shuffleboard doesn't close completely
**Describe the bug**  

If the layout isn't changed, shuffleboard won't completely exit.
git bisect shows this was broken by #701 

**To Reproduce**  
1.start shuffleboard from the command line without a robot connected (observe NT connection attempts continually in terminal
2. click the close button without changing anything
3. observe that NT connection attemps continue in terminal, despite the fact that 

**Expected behavior**  
All activity in the terminal should end and the commandline should return.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java version: 11.0.8

**Additional context**  
If you change the layout, then shuffleboard will close cleanly

### PR DESCRIPTION
**Pull request by sciencewhiz**
Fixes #708

### CODE REVIEW

File: app/src/main/java/edu/wpi/first/shuffleboard/app/Shuffleboard.java [hunk 1]
```diff
@@ -131,6 +131,7 @@ public void start(Stage primaryStage) {
     primaryStage.setOnCloseRequest(closeEvent -> {
       if (!AppPreferences.getInstance().isConfirmExit() || mainWindowController.isSaved()) {
```
Comment (AustinShalit) [inline app/src/main/java/edu/wpi/first/shuffleboard/app/Shuffleboard.java:132]: Is it better to reverse the logic of this if statement to gate the dialog and use the `Platform.exit()` on line 157?

Comment (sciencewhiz) [reply app/src/main/java/edu/wpi/first/shuffleboard/app/Shuffleboard.java:132]: I did that, and the cancel button stopped working (shuffleboard still exited). Haven't figured that out yet.

**Review by AustinShalit — APPROVED** [review]
