### PR TITLE
ScrollPane and height fixes for the gallery

### LINKED ISSUE #25: Widget palette needs a scrollbar if it doesn't all fit
When there are more widgets vertically in the palette than fit in the window there should be a scrollbar.

### PR DESCRIPTION
**Pull request by nightpool**
Now widgets fill the whole vbox, and they don't get super huge anymore. Also, the pane will scroll if the number of widgets is too large.

closes #25

### CODE REVIEW

**Comment by AustinShalit** [comment]
The width of the pane is still a little large:
untitled

**Comment by nightpool** [comment]
passes on linux, fails on mac

File: src/main/java/edu/wpi/first/shuffleboard/components/WidgetGallery.java [hunk 1]
```diff
@@ -35,10 +36,10 @@ public WidgetGallery() {
    */
   public void loadWidgets(Collection<WidgetType> widgets) {
     widgets.stream().map(WidgetType::get)
-            .peek(widget -> {
+            .peek(widget ->
               DummySource.forTypes(widget.getDataTypes())
-                         .ifPresent(widget::setSource);
-            })
+                         .ifPresent(widget::setSource)
+            )
```
Comment (SamCarlberg) [inline src/main/java/edu/wpi/first/shuffleboard/components/WidgetGallery.java]: random style change?

Comment (nightpool) [inline src/main/java/edu/wpi/first/shuffleboard/components/WidgetGallery.java]: yes?
