### PR TITLE
Check for invalid NT value

### LINKED ISSUE #758: NT NPE
No errors appear in the UI, but these errors are printed a lot when running via CLI.
```
WARNING: Uncaught exception on JavaFX Application Thread
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "edu.wpi.first.networktables.NetworkTableValue.getValue()" is null
        at edu.wpi.first.shuffleboard.plugin.networktables.util.NetworkTableUtils.dataTypeForEntry(NetworkTableUtils.java:55)
        at edu.wpi.first.shuffleboard.plugin.networktables.sources.NetworkTableSourceType.dataTypeForSource(NetworkTableSourceType.java:154)
```

@PeterJohnson is something here wrong with how NT4 is used?

### PR DESCRIPTION
**Pull request by Starlight220**
Fixes #758

### CODE REVIEW

File: plugins/networktables/src/main/java/edu/wpi/first/shuffleboard/plugin/networktables/util/NetworkTableUtils.java [hunk 1]
```diff
@@ -52,7 +52,10 @@ public static DataType dataTypeForEntry(String key) {
       return DataTypes.Map;
     }
     if (rootTable.containsKey(normalKey)) {
-      return DataTypes.getDefault().forJavaType(rootTable.getEntry(normalKey).getValue().getValue().getClass()).get();
+      var ntValue = rootTable.getEntry(normalKey).getValue();
+      if (ntValue.isValid()) {
+        return DataTypes.getDefault().forJavaType(ntValue.getValue().getClass()).get();
+      }
```
Comment (PeterJohnson) [inline plugins/networktables/src/main/java/edu/wpi/first/shuffleboard/plugin/networktables/util/NetworkTableUtils.java:58]: It feels like this shouldn’t fall through (to the if subtable comparison), and instead should immediately return null.
